### ISSUE TITLE
How to run prefill phase of inference benchmark?

### ISSUE THREAD

**Issue by mansur20478** [HazyResearch/based#13]
Hi, I want to test how much time it takes for prefilling phase. 
I want to test it with Llama2-7B model, and compare Based against FlashAttention.
How can I do it? 
I want to test it with different sequence lengths and number of batches.
It seems that I need to modify based_inference.py. However, I am not even able to install it because there is no "test_build_utils" library.

**Comment by simran-arora** [comment]
Hi - we are still preparing the release of the library we used to develop this kernel, as indicated in the README in the benchmarks folder. It will be released soon.

**Comment by simran-arora** [comment]
We have now released the source code for the prefill kernel: https://github.com/HazyResearch/ThunderKittens
