### ISSUE TITLE
a question, thank you for your reply

### ISSUE THREAD

**Issue by zhouyuan888888** [HazyResearch/based#15]
Hi, thank you for your nice work. I have a question about training. If I want to train your model on the pile-uncopyrighted dataset (just uncopyrighted pile), how should I prepare or pre-process the dataset?

**Comment by simran-arora** [comment]
Hi!
The option that we used was to follow the EleutherAI tokenization instructions provided here (prepare data): https://github.com/EleutherAI/gpt-neox
We then plugged in the file paths for the resulting train, val, and test splits here: https://github.com/HazyResearch/based/blob/f6552fa4de30151aa44b09b92c931d186fd34c17/train/datamodules/language_modeling_neox.py#L74

Our code base also supports tokenization for any hugging face dataset without any additional effort on your part. E.g., if you want to try Fine Web, Slim Pajama, etc. 
- This is the code that does the tokenization: https://github.com/HazyResearch/based/blob/f6552fa4de30151aa44b09b92c931d186fd34c17/train/datamodules/language_modeling_hf.py#L41
- This style of data config, where you can replace the dataset_name (and dataset_config_name if relevant) to the hugging face dataset that you choose, would work without any additional effort: https://github.com/HazyResearch/based/blob/f6552fa4de30151aa44b09b92c931d186fd34c17/train/configs/datamodule/wikitext103.yaml#L1
- And you just point to that data config you constructed here before launching: https://github.com/HazyResearch/based/blob/f6552fa4de30151aa44b09b92c931d186fd34c17/train/configs/experiment/example/based-360m.yaml#L4

**Comment by zhouyuan888888** [comment]
So thank you for your timely reply!

**Comment by lisc110h** [comment]
I am currently trying to train a model from scratch using the Pile dataset. I would like to add that it was necessary to run `make` at `based/train/datamodules/neox_utils` to build `helpers.cpp`.
